### ISSUE TITLE
inconsistency of workshops on website

### ISSUE THREAD

**Issue by danielskatz** [si2-urssi/website#33]
In the top set of links, we have a workshops link to http://urssi.us/workshops/ that lists 4 workshops, but not the final Chicago one.
In the footer, we list 3 workshops, not the incubator one and not the final Chicago one.

**Comment by danielskatz** [comment]
Also, each workshop page could use a bit of work to point to the blog post about it and where details can be found, changing the tense to past from future as well.

**Comment by karthik** [comment]
> but not the final Chicago one.
> In the footer, we list 3 workshops, not the incubator one and not the final Chicago one.

Because we never wrote a general post for the final one (since it was invite only for the PIs/SP/AB). We can't list something there unless there is also a blog post.

**Comment by danielskatz** [comment]
I don't understand - none of the 4 workshops linked from the link at the top or 3 linked directly at the bottom go to blog posts now.

**Comment by karthik** [comment]
Can you post some screenshots and examples? I dont quite follow you. 

> I don't understand - none of the 4 workshops linked from the link at the top or 3 linked directly at the bottom go to blog posts now.


They all go to the blog posts for me.

**Comment by danielskatz** [comment]
The top link here:
<img width="1361" alt="Screen Shot 2019-07-31 at 1 43 51 PM" src="https://user-images.githubusercontent.com/2913845/62238944-9274b100-b399-11e9-95f4-ce9efa88c388.png">
goes to this page:
<img width="1058" alt="Screen Shot 2019-07-31 at 1 45 22 PM" src="https://user-images.githubusercontent.com/2913845/62238966-9dc7dc80-b399-11e9-8e0a-1a362ef38c9a.png">
This shows that we had 4 workshops (not 5 - there's no link to the fifth meeting which could point to https://github.com/si2-urssi/final_workshop)

None of these 4 links go to the blog posts that talk about the results of the workshops, they go to the workshop pages instead, and 3 of the 4 workshop pages are written in the future tense.

For example, the top link goes to this pre-meeting page:

<img width="1216" alt="Screen Shot 2019-07-31 at 1 45 40 PM" src="https://user-images.githubusercontent.com/2913845/62239008-b0421600-b399-11e9-8828-8839fdeaa6a9.png">

The one meeting page that looks good as a model is the one from the first workshop, which does talk about and link to the blog post about the meeting, and is in the past test:

<img width="1073" alt="Screen Shot 2019-07-31 at 1 48 46 PM" src="https://user-images.githubusercontent.com/2913845/62239200-0a42db80-b39a-11e9-88b8-7ca8b1fa6604.png">

Also, the URSSI footer:

<img width="1268" alt="Screen Shot 2019-07-31 at 1 52 42 PM" src="https://user-images.githubusercontent.com/2913845/62239446-80dfd900-b39a-11e9-87f3-5db26b01469f.png">

only has links to 3 of the 5 workshops, not to the incubator workshop and not to the final workshop/meeting.

**Comment by karthik** [comment]
> there's no link to the fifth meeting which could point to https://github.com/si2-urssi/final_workshop

Unless someone writes a blog post under [`content/workshops/`](https://github.com/si2-urssi/website/tree/master/content/workshops), nothing will appear here. This page is autogenerated from that folder. So someone has to create a blog post there.

> None of these 4 links go to the blog posts that talk about the results of the workshops, they go to the workshop pages instead, and 3 of the 4 workshop pages are written in the future tense.

Correct. That is how we wrote these. These are announcements written under `content/workshops/`. We wrote the results under `content/blog`. So one could edit these posts and add a note the end saying the results of the meeting are {insert link to respective meeting summary}.

> only has links to 3 of the 5 workshops, not to the incubator workshop and not to the final workshop/meeting.

Again, we never wrote a blog post for the final workshop. We just have a github repo and invited people. If you want a blog post for the even that has passed, you have to write one under `content/workshops` then link that here.

**Comment by danielskatz** [comment]
I've made changes to fix/add these pages
